# Generated by Django 6.0.5 on 2026-06-07 02:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('championnat', 'championnat'), ('coupe', 'coupe'), ('élimination directe', 'élimination directe'), ('elimination directe', 'elimination directe')], max_length=50)),
                ('sport', models.CharField(choices=[('Football', 'Football'), ('Basketball', 'Basketball'), ('Handball', 'Handball'), ('Volleyball', 'Volleyball')], max_length=50)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('rules', models.TextField()),
                ('status', models.CharField(choices=[('Planifié', 'Planifié'), ('Planifie', 'Planifie'), ('En cours', 'En cours'), ('Terminé', 'Terminé'), ('Termine', 'Termine')], max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-startDate', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('number', models.PositiveSmallIntegerField()),
                ('position', models.CharField(max_length=100)),
                ('className', models.CharField(max_length=255)),
                ('photoUrl', models.URLField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['team__name', 'number', 'lastName'],
            },
        ),
        migrations.CreateModel(
            name='SportNotification',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('match_update', 'match_update'), ('schedule', 'schedule'), ('result', 'result'), ('announcement', 'announcement')], max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('isRead', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('motDePasse', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('Administrateur', 'Administrateur'), ('Responsable sportif', 'Responsable sportif'), ('Capitaine equipe', 'Capitaine equipe'), ('Étudiant', 'Étudiant'), ('Etudiant', 'Etudiant')], max_length=50)),
                ('etablissement', models.CharField(blank=True, choices=[('Saint Jean Ingénieur', 'Saint Jean Ingénieur'), ('Saint Jean Ingenieur', 'Saint Jean Ingenieur'), ('Saint Jean School of Management', 'Saint Jean School of Management'), ('Prépa Vogt', 'Prépa Vogt'), ('Prepa Vogt', 'Prepa Vogt'), ('CPGE', 'CPGE'), ('Prépa Saint Jean Douala', 'Prépa Saint Jean Douala'), ('Prepa Saint Jean Douala', 'Prepa Saint Jean Douala')], max_length=100)),
                ('avatarUrl', models.URLField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['lastName', 'firstName'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('etablissement', models.CharField(choices=[('Saint Jean Ingénieur', 'Saint Jean Ingénieur'), ('Saint Jean Ingenieur', 'Saint Jean Ingenieur'), ('Saint Jean School of Management', 'Saint Jean School of Management'), ('Prépa Vogt', 'Prépa Vogt'), ('Prepa Vogt', 'Prepa Vogt'), ('CPGE', 'CPGE'), ('Prépa Saint Jean Douala', 'Prépa Saint Jean Douala'), ('Prepa Saint Jean Douala', 'Prepa Saint Jean Douala')], max_length=100)),
                ('filiere', models.CharField(max_length=255)),
                ('logoColor', models.CharField(default='#38bdf8', max_length=40)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captained_teams', to='sport.player')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='sport.team'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('scoreA', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('scoreB', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('pitch', models.CharField(max_length=255)),
                ('referee', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Planifié', 'Planifié'), ('Planifie', 'Planifie'), ('En cours', 'En cours'), ('Terminé', 'Terminé'), ('Termine', 'Termine'), ('Reporté', 'Reporté'), ('Reporte', 'Reporte')], default='Planifié', max_length=50)),
                ('reportReason', models.TextField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='sport.competition')),
                ('teamA', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='sport.team')),
                ('teamB', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='sport.team')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='GoalRecord',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('minute', models.PositiveSmallIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='sport.match')),
                ('scorer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='sport.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='sport.team')),
            ],
            options={
                'ordering': ['minute', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CardRecord',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('yellow', 'yellow'), ('red', 'red')], max_length=20)),
                ('minute', models.PositiveSmallIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='sport.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='sport.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='sport.team')),
            ],
            options={
                'ordering': ['minute', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='sport.user')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('team', 'number'), name='unique_player_number_by_team'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('teamA', models.F('teamB')), _negated=True), name='match_requires_two_distinct_teams'),
        ),
    ]
